CREATE TABLE CATEGORY(
    CategoryID INT,
    Newsppr_Category VARCHAR(50),
    PRIMARY KEY(CategoryID)
);
CREATE TABLE NEWSPAPER( Name Varchar(50) NOT NULL, Published_Date DATE NOT NULL, Language Varchar(50) NOT NULL, CategoryID INT NOT NULL, NewspprID INT NOT NULL, FOREIGN KEY(CategoryID) REFERENCES CATEGORY(CategoryID),PRIMARY KEY(CategoryID,NewspprID));
CREATE TABLE CONTENT( ArticleID int NOT NULL, CategoryID int NOT NULL, NewspprID int NOT NULL, Article Varchar(100) NOT NULL, FOREIGN KEY(CategoryID) REFERENCES CATEGORY(CategoryID) , PRIMARY KEY(ArticleID) );
INSERT INTO CATEGORY VALUES(1,'SPORTS');
INSERT INTO CATEGORY values (2,'BOLLYWOOD');
INSERT INTO CATEGORY values (3,'POLITICS');
INSERT INTO NEWSPAPER values ('TOI','2022-01-31','ENGLISH',1,1);
INSERT INTO NEWSPAPER values ('TOI','2022-01-31','ENGLISH',2,1);

INSERT INTO CONTENT values (1,1,1,'Sachin scored a century');
INSERT INTO CONTENT values (2,2,1,'NEW MOVIES THIS MOTNH');